# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 03:42
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[(b'tweets_mine', b'My tweets'), (b'search', b'Search term'), (b'list', b'List')], max_length=100)),
                ('list_slug', models.CharField(max_length=100)),
                ('list_name', models.CharField(max_length=100)),
                ('search_term', models.CharField(max_length=100)),
                ('collection_id', models.CharField(max_length=100)),
                ('collection_name', models.CharField(max_length=100)),
                ('retweet_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('favorite_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('engagement_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('block_words', models.CharField(blank=True, max_length=2400, null=True)),
                ('include_retweets', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime.today)),
                ('created_by', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_collection_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='modified_collection_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
